compile: null
data:
  drop_last: true
  num_workers: 32
  pad_direction: right
  paths:
  - https://olmo-data.org/preprocessed/olmo-mix/v1_5/gpt-neox-20b-pii-special/part-000-00000.npy
  - https://olmo-data.org/preprocessed/olmo-mix/v1_5/gpt-neox-20b-pii-special/part-000-00000.npy
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 8
  timeout: 0
device_eval_batch_size: ${device_train_microbatch_size}
device_train_microbatch_size: 2
dry_run: false
eval_interval: ${save_interval}
eval_subset_num_batches: -1
evaluators:
- data:
    datasets:
      v3-small-c4_en-validation:
      - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/c4_en/val/part-0-00000.npy
      v3-small-dolma_books-validation:
      - https://olmo-data.org/eval-data/perplexity/v3_small_gptneox20b/dolma_books/val/part-0-00000.npy
    drop_last: true
    num_workers: 0
  label: all-small-ppl-validation
- label: piqa
  type: downstream
- label: hellaswag
  type: downstream
- label: winogrande
  type: downstream
- label: openbook_qa
  type: downstream
- label: boolq
  type: downstream
- label: sciq
  type: downstream
- label: arc_easy
  type: downstream
- label: arc_challenge
  type: downstream
- label: mmlu_stem
  type: downstream
- label: mmlu_humanities
  type: downstream
- label: mmlu_social_sciences
  type: downstream
- label: mmlu_other
  type: downstream
- label: mmlu_stem_var
  type: downstream
- label: mmlu_humanities_var
  type: downstream
- label: mmlu_social_sciences_var
  type: downstream
- label: mmlu_other_var
  type: downstream
- label: mmlu_stem_mc_5shot
  type: downstream
- label: mmlu_humanities_mc_5shot
  type: downstream
- label: mmlu_social_sciences_mc_5shot
  type: downstream
- label: mmlu_other_mc_5shot
  type: downstream
- label: squad
  type: downstream
- label: mathqa
  type: downstream
- label: math_algebra
  type: downstream
- label: math_counting_and_prob
  type: downstream
- label: math_geometry
  type: downstream
- label: math_intermediate_algebra
  type: downstream
- label: math_num_theory
  type: downstream
- label: math_prealgebra
  type: downstream
- label: math_precalc
  type: downstream
- label: math_asdiv
  type: downstream
- label: arithmetic_2da
  type: downstream
- label: arithmetic_2ds
  type: downstream
- label: arithmetic_3da
  type: downstream
- label: arithmetic_3ds
  type: downstream
- label: arithmetic_4da
  type: downstream
- label: arithmetic_4ds
  type: downstream
- label: arithmetic_5da
  type: downstream
- label: arithmetic_5ds
  type: downstream
- label: arithmetic_2dm
  type: downstream
- label: arithmetic_1dc
  type: downstream
fsdp:
  precision: mixed
  wrapping_strategy: by_block_and_size
global_train_batch_size: 1024
load_path: null
max_duration: 50e9T
max_grad_norm: 1.0
max_grad_norm_ratio: null
model:
  activation_type: swiglu
  alibi: true
  alibi_bias_max: 8.0
  attention_dropout: 0.0
  attention_layer_norm: false
  block_type: sequential
  d_model: 96
  embedding_dropout: 0.0
  embedding_size: 50304
  eos_token_id: 0
  flash_attention: false
  include_bias: false
  init_device: meta
  init_fn: mitchell
  layer_norm_type: default
  max_sequence_length: 2048
  mlp_ratio: 4
  multi_query_attention: false
  n_heads: 4
  n_layers: 8
  pad_token_id: 1
  residual_dropout: 0.0
  rope: false
  vocab_size: 50280
  weight_tying: false
no_pre_train_checkpoint: true
optimizer:
  betas:
  - 0.9
  - 0.95
  learning_rate: 0.0005
  name: adamw
  weight_decay: 0.1
precision: amp_bf16
remote_save_folder: null
reset_optimizer_state: false
reset_trainer_state: false
restore_dataloader: false
run_name: no_code_olmo-11m
save_folder: /data/tain
save_interval: 1000
save_interval_unsharded: 5000
save_num_checkpoints_to_keep: 9
save_num_unsharded_checkpoints_to_keep: -1
save_overwrite: true
scheduler:
  alpha_f: 0
  name: linear_with_warmup
  t_warmup: 100
seed: 61394
sharded_checkpointer: olmo_core
speed_monitor:
  window_size: 1
stop_at: 11931
time_limit: null
tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right
wandb:
  entity: predict-data-ablations
  name: no_code_olmo-11m
  project: predict-data-ablations
